### ISSUE TITLE
夸克获取分享链接为空

### ISSUE THREAD

**Issue by AMBITION-Z** [superBiuBiuMan/sharelink#4]
默认等待时间是1000，按照作者说的尽量不要设置太低，但是我的不知道为什么，这个值越高采集不到链接的越多，反而值越小（500）能采集到就比较多，所以这儿有点迷糊，不清楚是什么原因

**Comment by superBiuBiuMan** [comment]
可能是夸克需要调用2次接口,然后如果调用间隔太长就会出问题,我这个星期看看

**Comment by superBiuBiuMan** [comment]
更新版本，修复好了，忘记发了
